# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- pwsh: |
    # az artifacts universal publish --feed 'test' --scope 'project' --name 'microsoft_insights_actiongroups' --version '0.0.1-test2' --path 'Modules/Microsoft.Insights/actionGroups' --verbose

    $VstsOrganization = '$(System.CollectionUri)'.Split('/')[-2]
    $VstsProject = '$(System.TeamProject)'
    $VstsFeedName = 'test'
    "Org is: $VstsOrganization"
    "Project is: $VstsProject"

    $head = @{ Authorization = "Bearer $env:PAT" }
    $url = "https://feeds.dev.azure.com/$VstsOrganization/$VstsProject/_apis/packaging/Feeds?api-version=7.1-preview.1"
    $feed = Invoke-RestMethod -Uri $url -Method Get -Headers $head -ContentType application/json
    "Feeds:"
    $Feed

    " ------------------- "

    $VstsFeedName = 'test'
    "Feed: $VstsFeedName"
    $head = @{ Authorization = "Bearer $env:PAT" }
    $url = "https://feeds.dev.azure.com/$VstsOrganization/$VstsProject/_apis/packaging/Feed/$VstsFeedName?api-version=7.1-preview.1"
    $feed = Invoke-RestMethod -Uri $url -Method Get -Headers $head -ContentType application/json
    "Feed [$VstsFeedName] is:"
    $Feed

    " ------------------- "

    $VstsFeedName = 'test2'
    "Feed: $VstsFeedName"
    $url = "https://feeds.dev.azure.com/$VstsOrganization/$VstsProject/_apis/packaging/Feed/$VstsFeedName?api-version=7.1-preview.1"
    $feed = Invoke-RestMethod -Uri $url -Method Get -Headers $head -ContentType application/json
    "Feed [$VstsFeedName] is:"
    $Feed

    " ------------------- "

    $VstsFeedName = 'test2'
    "Feed: $VstsFeedName"
    $url = "https://feeds.dev.azure.com/$VstsOrganization/_apis/packaging/Feed/$VstsFeedName?api-version=7.1-preview.1"
    $feed = Invoke-RestMethod -Uri $url -Method Get -Headers $head -ContentType application/json
    "Feed [$VstsFeedName] is:"
    $Feed

  env:
    PAT: $(System.AccessToken)
    # AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
