name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

pr: none
trigger: none

parameters:
  - name: ServiceConnection
    displayName: Service Connection name
    type: string
  - name: TemplateParameterFilePath
    displayName: Parameter file path
    type: string
  - name: Location
    displayName: Location of the deployed resources
    type: string
    default: "westeurope"
    values:
      - "westeurope"

variables:
  TemplateFile: 'Solutions\Synapse\main.bicep'

pool:
  vmImage: ubuntu-latest

stages:
- stage: Deploy
  displayName: Deploy solution
  jobs:
  - job: Deploy
    displayName: Deploy solution
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    steps:
    - task: AzurePowerShell@5
      displayName: Deploy solution
      inputs:
        azureSubscription: ${{ parameters.ServiceConnection }}
        ScriptType: 'InlineScript'
        azurePowerShellVersion: 'LatestVersion'
        pwsh: true
        Inline: |
          $DeploymentInputs = @{
              Name                  = "Sub-$(-join (Get-Date -Format yyyyMMddTHHMMssffffZ)[0..63])"
              Location              = '${{ parameters.Location }}'
              TemplateFile          = '$(TemplateFile)'
              TemplateParameterFile = '${{ parameters.TemplateParameterFilePath }}'
              Verbose               = $true
              ErrorAction           = 'Stop'
          }

          Write-Output 'Subscription deployment using:'
          $DeploymentInputs

          New-AzSubscriptionDeployment @DeploymentInputs
